spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/YHBasic
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true // 콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.

logging.level:
  org.hibernate.SQL: debug